public with sharing class CorporateLinkage 
{
    public String dunsNumber {get; set;}
    public String enqDunsNumber {get; set;}
    public String primaryName {get; set;}
	public String branchIndicator {get; set;}
    public String businessStructure {get; set;}
    public String locationStatus {get; set;}
    public String countryCode {get; set;}
    public String siteName {get; set;}
    public String siteDUNS {get; set;}
    public String siteCountry {get; set;}
    public String hqDUNS {get; set;}
    public String hqName {get; set;}
    public String hqCountry {get; set;}
    public String domesticUltimateName {get; set;}
    public String domesticUltimateDUNS {get; set;}
    public String domesticUltimateCountry {get; set;}
    public String globalUltimateName {get; set;}
    public String globalUltimateDUNS {get; set;}
    public String globalUltimateCountry {get; set;}
    public Boolean hasCorporateLinkage {get; set;}
}