/*
Changes History
---------------------------------------------------------------------------------------------------
Date:         |   Author            | Initials | Description
11-11-2014    | Abdul Aziz Khatri   |  AAK     | Created Model for holding Data.com Company info
*/

public class RDatacom_Company
{
    public String CompanyName;
    public String state;
    public String country;    
    public String street;    
    public String city;
    public String zipCode;    
    public String Phone;
    
}