@isTest
private Class UpdAccLstActDtEvtBatchTest{
    static testmethod void unitTest()
    {
      UpdAccLstActDtEvtBatch batchEvent = new UpdAccLstActDtEvtBatch ();
      //Test.startTest();
      
      //UpdAccLstActDtEvtBatchHelper batchEvent = new UpdAccLstActDtEvtBatchHelper(); 
      //batchEvent.query='select Id, WhatId, WhoId, ActivityDate, StartDateTime, EndDateTime, Type from Event where ActivityDate = Today';
      //Id BatchprocessId = database.executebatch(batchEvent,100);
      
      //Test.StopTest();
    }
}